# Generated by Django 4.1.7 on 2023-04-30 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='edited',
        ),
    ]
