# Generated by Django 4.1.7 on 2023-05-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_retwitted',
            field=models.BooleanField(default=False),
        ),
    ]
