# Generated by Django 4.1.7 on 2023-05-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweet_is_retwitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='is_retwitted',
        ),
    ]
