# Generated by Django 4.1.7 on 2023-05-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_tweetimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tweetImages'),
        ),
    ]
