# Generated by Django 4.1.7 on 2023-05-16 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0009_remove_tweet_likes_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='likes_users',
            field=models.ManyToManyField(related_name='likes_tweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
