# Generated by Django 4.2.1 on 2023-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_remove_tweet_likes_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='responses',
            field=models.IntegerField(null=True),
        ),
    ]
