# Generated by Django 4.1.7 on 2023-05-26 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_alter_tweet_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetimage',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tweets.tweet'),
        ),
    ]
