# Generated by Django 4.1.7 on 2023-05-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0015_alter_tweetimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tweetVideos'),
        ),
    ]
