# Generated by Django 4.1.7 on 2023-05-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0016_tweetimage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='haveMultimedia',
            field=models.BooleanField(default=False),
        ),
    ]
