# Generated by Django 4.1.7 on 2023-05-27 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0017_tweet_havemultimedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='haveMultimedia',
        ),
    ]
