# Generated by Django 4.1.7 on 2023-05-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profiles_retweets'),
        ('tweet_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet_profile',
            name='retwitted_by',
            field=models.ManyToManyField(related_name='retweet_users', to='profiles.profiles'),
        ),
    ]
