# Generated by Django 4.1.7 on 2023-05-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_alter_tweetimage_image'),
        ('tweet_profiles', '0002_tweet_profile_retwitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet_profile',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='tweets.tweetimage'),
        ),
    ]
