# Generated by Django 4.1.7 on 2023-05-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_verfifyrequests'),
        ('tweet_profiles', '0003_tweet_profile_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet_profile',
            name='images',
        ),
        migrations.AddField(
            model_name='tweet_profile',
            name='likes_users',
            field=models.ManyToManyField(related_name='likes_tweets', to='profiles.profiles'),
        ),
    ]
