# Generated by Django 4.1.7 on 2023-05-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_profiles', '0006_tweet_profile_likes_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet_profile',
            name='haveMultimedia',
            field=models.BooleanField(default=False),
        ),
    ]
