# Generated by Django 4.2.1 on 2023-06-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_profiles', '0007_tweet_profile_havemultimedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet_profile',
            name='parent_tweet',
            field=models.IntegerField(null=True, verbose_name='self'),
        ),
    ]
