# Generated by Django 4.2.1 on 2023-06-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_profiles', '0008_tweet_profile_parent_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet_profile',
            name='parent_tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweet_profiles.tweet_profile'),
        ),
    ]
