# Generated by Django 4.1.7 on 2023-04-16 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30, null=True)),
                ('biography', models.TextField(blank=True, default='', max_length=250, null=True)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='profileImages')),
                ('followers', models.IntegerField(default=0)),
                ('birthday', models.DateField(default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed_users', models.ManyToManyField(blank=True, related_name='following', to='profiles.profiles')),
                ('followers_users', models.ManyToManyField(blank=True, related_name='followage', to='profiles.profiles')),
                ('keeps', models.ManyToManyField(blank=True, related_name='kept_by_profiles', to='tweets.tweet')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
