# Generated by Django 4.1.7 on 2023-04-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='webSite',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
