# Generated by Django 4.2 on 2023-04-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='followers_users',
            field=models.ManyToManyField(blank=True, related_name='followers_users', to='profiles.profiles'),
        ),
    ]
