# Generated by Django 4.1.7 on 2023-04-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
