# Generated by Django 4.1.7 on 2023-04-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profiles_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='profileBanner',
            field=models.ImageField(blank=True, null=True, upload_to='profileBanners'),
        ),
    ]
