# Generated by Django 4.1.7 on 2023-05-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweet_is_retwitted'),
        ('profiles', '0004_profiles_profilebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='retweets',
            field=models.ManyToManyField(blank=True, related_name='retweets_by_profiles', to='tweets.tweet'),
        ),
    ]
