# Generated by Django 4.1.7 on 2023-05-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_alter_tweet_responses'),
        ('profiles', '0007_verfifyrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='like_tweets',
            field=models.ManyToManyField(blank=True, related_name='liked', to='tweets.tweet'),
        ),
    ]
