# Generated by Django 4.1.7 on 2023-05-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profiles_like_tweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='darkMode',
            field=models.BooleanField(default=False),
        ),
    ]
