# Generated by Django 4.2.1 on 2023-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profiles_darkmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='strikes',
            field=models.IntegerField(default=3),
        ),
    ]
