# Generated by Django 4.2.1 on 2023-06-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profiles_strikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
