# Generated by Django 4.2.1 on 2023-06-07 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profiles_banned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='username',
            new_name='atName',
        ),
    ]
