# Generated by Django 4.2.1 on 2023-06-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_rename_username_profiles_atname'),
    ]

    operations = [
        migrations.CreateModel(
            name='unbanRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles')),
            ],
        ),
    ]
